---
  - name: copy demo
    hosts: webservers
    tasks:
      - name: copy ansibble.cfg file
        ansible.builtin.copy:
          content: "This file copied using Ansible copy module"
          dest: /home/student/myimpfile.txt
          owner: student
          group: devops
          mode: u+rw,g+rw,o-rw
          setype: samba_share_t
