---
  - name: demo of ansible facts 
    hosts: servera.lab.example.com
    gather_facts: false
    tasks:
      - name: collecting info 
        ansible.builtin.setup:
          gather_subset:
            - "!all"
            - "hardware"
            - "network"
