---
  - name: colelcting facts
    hosts: servera.lab.example.com
    tasks:
      - name: collect facts
        ansible.builtin.debug:
          var: ansible_facts['ansible_local']['servera']['general']['pkg1']
