---
  - name: verify simple-agent rpm installation
    hosts: servera.lab.example.com
    tasks:
      - name: collect packages facts
        ansible.builtin.package_facts:
        
      - name: verify simple agent installled or not
        ansible.builtin.debug:
          var: ansible_facts['packages']['simple-agent']
