---
  - name: arbitrrary modules
    hosts: serverb.lab.example.com
    tasks:
      - name: execute a cmd
        ansible.builtin.debug:
          var: ansible_facts['hostname']
          #verbosity: 2
